"""Update Report model schema

Revision ID: 1809851f59b9
Revises: 
Create Date: 2025-03-04 07:29:41.180167

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '1809851f59b9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('report', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_phishing', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('confidence_score', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('reported_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('reporter_email', sa.String(length=120), nullable=True))
        batch_op.alter_column('report_type',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
        batch_op.alter_column('expected_result',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
        batch_op.alter_column('actual_result',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
        batch_op.drop_column('updated_at')
        batch_op.drop_column('status')
        batch_op.drop_column('created_at')
        batch_op.drop_column('email')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('report', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.alter_column('actual_result',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
        batch_op.alter_column('expected_result',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
        batch_op.alter_column('report_type',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
        batch_op.drop_column('reporter_email')
        batch_op.drop_column('reported_at')
        batch_op.drop_column('confidence_score')
        batch_op.drop_column('is_phishing')

    # ### end Alembic commands ###
